import type { LovePageInput } from "@/lib/love-page-schema";

export const gameLocales = ["uk", "ru", "en"] as const;
export type GameLocale = (typeof gameLocales)[number];

export function isGameLocale(value: unknown): value is GameLocale {
  return typeof value === "string" && gameLocales.includes(value as GameLocale);
}

export const gameCopy = {
  uk: {
    rules: "Правила комбінацій",
    compliment: "Комплімент",
    grandPrize: "Головний подарунок",
    miss: "Хоч один — усе пропало",
    introKicker: "Три оберти · одна історія",
    introTitle: "сьогодні удача закохана в тебе",
    begin: "Почати історію",
    spinCount: (round: number) => `Оберт ${round} із 3`,
    roundTitles: ["Почнемо з маленького дива", "Серце підказує: ще раз", "Здається, усе збіглося…"],
    machineHint: "Серце знає правильний знак",
    falseAlarm: "Ой… здається, усе пропало?",
    win: "Твій виграш",
    next: "Ще один оберт",
    spinning: "Серце обирає…",
    lastChance: "Залишився останній шанс",
    spin: "Обертати",
    photoAlt: (name: string) => `Фото для ${name}`,
    certificate: "PDF-сертифікат",
    certificateAlt: (name: string) => `Відкрити сертифікат ${name}`,
    open: "Відкрити",
    withLove: "З любов’ю",
    replay: "Пережити ще раз",
  },
  ru: {
    rules: "Правила комбинаций",
    compliment: "Комплимент",
    grandPrize: "Главный подарок",
    miss: "Хотя бы одно — всё пропало",
    introKicker: "Три вращения · одна история",
    introTitle: "сегодня удача влюблена в тебя",
    begin: "Начать историю",
    spinCount: (round: number) => `Вращение ${round} из 3`,
    roundTitles: ["Начнём с малого чуда", "Сердце подсказывает: ещё раз", "Кажется, всё совпадает…"],
    machineHint: "Сердце знает правильный знак",
    falseAlarm: "Ой… кажется, всё пропало?",
    win: "Твой выигрыш",
    next: "Ещё одно вращение",
    spinning: "Сердце выбирает…",
    lastChance: "Остался последний шанс",
    spin: "Вращать",
    photoAlt: (name: string) => `Фото для ${name}`,
    certificate: "PDF-сертификат",
    certificateAlt: (name: string) => `Открыть сертификат ${name}`,
    open: "Открыть",
    withLove: "С любовью",
    replay: "Пережить ещё раз",
  },
  en: {
    rules: "Winning combinations",
    compliment: "Compliment",
    grandPrize: "Grand prize",
    miss: "One miss — all is lost",
    introKicker: "Three spins · one story",
    introTitle: "today luck is in love with you",
    begin: "Begin the story",
    spinCount: (round: number) => `Spin ${round} of 3`,
    roundTitles: ["Let's start with a little magic", "Your heart says: one more time", "Everything is falling into place…"],
    machineHint: "The heart knows the right sign",
    falseAlarm: "Oh… did we lose it all?",
    win: "Your prize",
    next: "One more spin",
    spinning: "The heart is choosing…",
    lastChance: "One last chance",
    spin: "Spin",
    photoAlt: (name: string) => `Photo for ${name}`,
    certificate: "PDF certificate",
    certificateAlt: (name: string) => `Open certificate ${name}`,
    open: "Open",
    withLove: "With love",
    replay: "Experience it again",
  },
} as const;

export const demoData: Record<GameLocale, LovePageInput> = {
  uk: {
    recipientName: "Кохана людино",
    introText: "Я приготував для тебе маленьку історію, де кожен оберт наближає нас одне до одного.",
    complimentOne: "Твоя усмішка робить звичайний день особливим.",
    complimentTwo: "Поруч із тобою хочеться зупинити час.",
    prizeTitle: "Вечір для нас двох",
    prizeMessage: "Обери день, а про все інше я подбаю.",
    senderName: "Твоя людина",
  },
  ru: {
    recipientName: "Любимый человек",
    introText: "Я приготовил для тебя маленькую историю, где каждое вращение сближает нас ещё сильнее.",
    complimentOne: "Твоя улыбка делает обычный день особенным.",
    complimentTwo: "Рядом с тобой хочется остановить время.",
    prizeTitle: "Вечер для нас двоих",
    prizeMessage: "Выбери день, а обо всём остальном я позабочусь.",
    senderName: "Твой человек",
  },
  en: {
    recipientName: "My favorite person",
    introText: "I made you a little story. Each spin brings us a little closer together.",
    complimentOne: "Your smile makes an ordinary day feel special.",
    complimentTwo: "With you, I wish time could stand still.",
    prizeTitle: "An evening for two",
    prizeMessage: "Pick the day. I'll take care of everything else.",
    senderName: "Your person",
  },
};
